### ISSUE TITLE
Use other selectors than <div>

### ISSUE THREAD

**Issue by LukyVj** [samthor/rippleJS#1]
Hey, your script is just wonderful!!
But I'd like to see it working with more selectors than `div`.

I'll tweak the code and I may send you a PR when it's done :)

**Comment by samthor** [comment]
Are you talking about how to host the ripple itself? It shouldn't matter - my examples even use `link` (since it's a small void element, aka one that doesn't need to be closed).

e.g.-

``` html
<button>
  Blah
  <link class="rippleJS" />
</button>
```

**Comment by LukyVj** [comment]
Well, I'll be more specific. 

I tried to use it on a `<figure>` element, and it wasn't working. I look into the code, 
and it seems the function `hasCss` is applied only to a `div` element.
https://github.com/samthor/rippleJS/blob/master/ripple.js#L13-L21

I thought it was why the ripple wasn't working. I assumed it was related to the `hasCss`function. 

Maybe I just don't get how you define the selector that will use the ripple.

**Comment by samthor** [comment]
Oh cool, there might be a problem there then. Could you share me any sample code that shows a problem with a `figure`?

So, the code mostly requires you to create a child element that holds the ripples. This might be confusing. You shouldn't apply `rippleJS` to the thing you want the effect on - you _must_ define a child element to contain them, since there's a lot of style implied by the `rippleJS` class.

**Comment by samthor** [comment]
Closing due to lack of information.
